import numpy as np
import cv2
import matplotlib.pyplot as plt
from scipy.optimize import minimize, rosen, rosen_der
#import Reconstruction
from Reconstruction import *
import Camera



"""3D RECONSTRUCTION.

These routines use code style based by the `Google Python
Style Guide`. Docstrings may extend over multiple lines. Sections are created
with a section header and a colon followed by a block of indented text.
for 

variables: lowercase with underscore in case of multiple words, avoid resuming if possible
	im
	im_1
	structure_homogeneous

Properties:	same style as variables

Attributes: all togheter, without underscore and the second word is always capitalized.
    imagemName
	imagePropertyParameters
    imagem

Classes: start with cls and uses UpperAndLower format
	clsParameterMacher

Objetcts: if possible, same name of the class without the cls marker. Always starts with capital case
	ParameterMatcher_<object_sub_name>
	ParameterMatcher_Flann
    

Examples: if possible define some example for routine usage
    obj = clsImageTest.clsImage(<filename>)
    tuple = obj.imageShape


Authors:  Define the name and alias here. any changes from the master branch must be signed by the alias and with date
    (LEO) Leonardo de Mello Honorio 
    (CHV) Carlos Henrique Valerio de Moraes

Last Modified:
    (LEO) : 23/02/2016

Version:
    v0.1


LIBRARIES VERSION USED LIBS: 
		see requirements.txt (automatically generated by visual studio virtual environments)

    

"""

#x0 = [1.3, 0.7, 0.8, 1.9, 1.2]
#res = minimize(rosen, x0, method='Nelder-Mead', tol=1e-6)



clsReconstruction.sparceRecostructionTrueCase('b4.jpg','b5.jpg','k_cam_hp.dat')

#clsReconstruction.NewMatching('b4.jpg','b5.jpg','k_cam_hp.dat')